import type { User, Issue } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@city.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    isAdmin: true,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'john@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    isAdmin: false,
    createdAt: '2024-02-15T00:00:00Z',
  },
  {
    id: '3',
    name: 'Jane Smith',
    email: 'jane@example.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    isAdmin: false,
    createdAt: '2024-03-20T00:00:00Z',
  },
];

export const mockIssues: Issue[] = [
  {
    id: '1',
    title: 'Large pothole on Main Street',
    description: 'There is a dangerous pothole near the intersection that needs immediate attention. It has been causing traffic issues and poses a risk to vehicles.',
    category: 'Pothole',
    status: 'In Progress',
    priority: 'High',
    location: {
      address: '123 Main Street, Downtown',
      latitude: 40.7128,
      longitude: -74.0060,
    },
    photos: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    reportedBy: '2',
    reportedByName: 'John Doe',
    createdAt: '2024-10-20T10:30:00Z',
    updatedAt: '2024-10-22T14:20:00Z',
    upvotes: 45,
    upvotedBy: ['2', '3'],
    comments: [
      {
        id: 'c1',
        issueId: '1',
        userId: '1',
        userName: 'Admin User',
        text: 'We have assigned a team to fix this issue. Expected completion by end of week.',
        createdAt: '2024-10-22T14:20:00Z',
      },
    ],
    assignedTo: 'Road Maintenance Team A',
  },
  {
    id: '2',
    title: 'Overflowing garbage bins',
    description: 'The garbage bins at Park Avenue have been overflowing for the past week, creating unhygienic conditions.',
    category: 'Garbage',
    status: 'Resolved',
    priority: 'Medium',
    location: {
      address: 'Park Avenue, Sector 5',
      latitude: 40.7580,
      longitude: -73.9855,
    },
    photos: ['https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=800'],
    reportedBy: '3',
    reportedByName: 'Jane Smith',
    createdAt: '2024-10-15T08:15:00Z',
    updatedAt: '2024-10-18T16:30:00Z',
    resolvedAt: '2024-10-18T16:30:00Z',
    upvotes: 28,
    upvotedBy: ['2', '3'],
    comments: [
      {
        id: 'c2',
        issueId: '2',
        userId: '1',
        userName: 'Admin User',
        text: 'Issue has been resolved. Increased collection frequency for this area.',
        createdAt: '2024-10-18T16:30:00Z',
      },
    ],
    assignedTo: 'Sanitation Department',
  },
  {
    id: '3',
    title: 'Streetlight not working',
    description: 'The streetlight at the corner of 5th Avenue and Oak Street has not been working for two weeks, making the area dark and unsafe at night.',
    category: 'Streetlight',
    status: 'Pending',
    priority: 'High',
    location: {
      address: '5th Avenue & Oak Street',
      latitude: 40.7489,
      longitude: -73.9680,
    },
    photos: ['https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800'],
    reportedBy: '2',
    reportedByName: 'John Doe',
    createdAt: '2024-10-23T19:45:00Z',
    updatedAt: '2024-10-23T19:45:00Z',
    upvotes: 12,
    upvotedBy: ['2'],
    comments: [],
  },
  {
    id: '4',
    title: 'Water leakage from pipe',
    description: 'Continuous water leakage from underground pipe causing flooding on the sidewalk.',
    category: 'Water Supply',
    status: 'In Progress',
    priority: 'High',
    location: {
      address: 'Maple Drive, Block C',
      latitude: 40.7306,
      longitude: -73.9352,
    },
    photos: ['https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=800'],
    reportedBy: '3',
    reportedByName: 'Jane Smith',
    createdAt: '2024-10-21T11:20:00Z',
    updatedAt: '2024-10-23T09:15:00Z',
    upvotes: 34,
    upvotedBy: ['2', '3'],
    comments: [
      {
        id: 'c3',
        issueId: '4',
        userId: '1',
        userName: 'Admin User',
        text: 'Water department team is on site working on repairs.',
        createdAt: '2024-10-23T09:15:00Z',
      },
    ],
    assignedTo: 'Water Department',
  },
  {
    id: '5',
    title: 'Blocked drainage causing flooding',
    description: 'The drainage system is completely blocked, and rainwater is not flowing, causing street flooding.',
    category: 'Drainage',
    status: 'Resolved',
    priority: 'Medium',
    location: {
      address: 'Riverside Road, Zone 2',
      latitude: 40.7614,
      longitude: -73.9776,
    },
    photos: ['https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800'],
    reportedBy: '2',
    reportedByName: 'John Doe',
    createdAt: '2024-10-12T14:30:00Z',
    updatedAt: '2024-10-17T10:45:00Z',
    resolvedAt: '2024-10-17T10:45:00Z',
    upvotes: 52,
    upvotedBy: ['2', '3'],
    comments: [
      {
        id: 'c4',
        issueId: '5',
        userId: '1',
        userName: 'Admin User',
        text: 'Drainage has been cleared and system is functioning normally.',
        createdAt: '2024-10-17T10:45:00Z',
      },
    ],
    assignedTo: 'Public Works Department',
  },
  {
    id: '6',
    title: 'Playground equipment damaged',
    description: 'Several swings are broken and the slide has sharp edges. Safety concern for children.',
    category: 'Parks',
    status: 'Pending',
    priority: 'Medium',
    location: {
      address: 'Central Park, Playground Area',
      latitude: 40.7812,
      longitude: -73.9665,
    },
    photos: ['https://images.unsplash.com/photo-1580056291219-6ec6e14b7ed5?w=800'],
    reportedBy: '3',
    reportedByName: 'Jane Smith',
    createdAt: '2024-10-24T07:00:00Z',
    updatedAt: '2024-10-24T07:00:00Z',
    upvotes: 8,
    upvotedBy: ['3'],
    comments: [],
  },
];
